language: java
addons:
  apt:
    packages:
    - xmlstarlet
    - graphviz
jdk:
- oraclejdk11
after_success:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- ./can_auto_deploy.sh && mvn deploy --settings settings.xml
env:
  global:
  - secure: hC6gKhcKEQpq/8p7o44eXZ8jzcYbXuYMr93NAdA//InSn4A12OQioVaGsbbz3BDstDlhNlJBp11wAHSWLpYeq4ajHIpL7QgDUILb3F4urgTNnHOFyC3zix/1N/QB/QJR6eCmAZsQd7UtgwBOkM/0Men5jwbKNAMRpJ+EqIIcDZ4Xj3/efRDG9hznyXiym1w3CcOhvdSaSDhlV+03UgBrOzzDw2Kfoaw1n6nQQEM8T2nm9o2gLmSB1EDwpRZX0iVNWdUUnnRBf8Wl0y75Ji3/29hOMhOcCPGBnJNkJY4Dg2imZNQHIPwjNfAtbl0Ezv/zwn+GHosOcMFRj14oiXEz3DfcpUcfk1LrhPt1TuNJNEhznYdgm750ydJwrTR/jWpttHdOyRnb+XIjxVpBdXHN0+wiMMLZbkN3ArvUjl1MX7ya2L4q06yLILOK6ZjDHGIwt/sUq5VMCxkwChUMAUpAnUU7yTEdJP3SKkqz+jRwogzETl/2mDVBlTCKmtsBONtHxbDVAIAF9GeL7Rxy4I4LzxkmuPAZtTz0CXJoBVzT31DqQxjQ7mGzFeHVZcO3W2VBweag5cBtCZWF8+Uv9OzpZhs8mDisGe6oip9kvP1TfviYaiIQfmy8YrzNoY0GJAxSS67z03hPyFNEC34stM2ORANBQa5+QcmdXBkBIs6pThk=
  - secure: fWi83Kd7gPLTJtQIeyqqwrOXgSe6tooQ5xOfPV1Th7McqIFQwNEOct6kqbXzq4c26Tsv+tiRA+Ea7m8hzU0Xo66HboaTyz88POsoecmsV4BWFfcovpgY5RiMm3QIj9/8QpdwuZBFLGfXMCmPZAUo9rQgnSqviF9wyIi58fM77EGeO2DPJd/pRu7C6cYE0QEa/E+5GXkzz/J7Jpiqwf6tC3c9e2WbG3+COjpFzH4xyDGXwQHF5JMaDJQT10OBA9bdZ1T92lsDUBW7R+Uatlr/cCg/bmCwAIRuIGv4kaI6CUxI7A4JPaHugXShRFcuK7EkkzfwGpvCqJgoz/BHfe2db5Miw5JJO7h6RYn4qLsEcGSRHWplrheoHsGCrFNJTNbzPcQ2bmIPTU3KTKtsLhBpdcvWRvFdvmZ5zMRI1GTOWSl6C1mepx7MjzEAHiYIqj6nURy4Y9I58vVrh4M1eNKoBgt31k98TmRYDnX+mKK9nwBvFdurblorrwpfIozKyd3aBKJmW9Jc6ZH/hscnbUgFnYt+9RE8xqGMuI80ZivM3hb6cDjOw+kGkA/SSTgW/yctuQsh3nnj8qXv5sbEU/dGxoVG+m/htg+KKXHhTiunjKG3UK3G7/LwPdFhHDa7o52n5j8BdpEXJQn4E2Pffx3Qc0J3slcuXDyNsdETvhBU8pg=
